name: luna
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.10
  flutter_hooks:
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  smooth_page_indicator: ^1.1.0
  envied: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  custom_lint:
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
